// <auto-generated />
using System;
using Fluxo.Lancamentos.Service.Shell.Resources.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fluxo.Lancamentos.Service.Migrations
{
    [DbContext(typeof(LancamentosDbContext))]
    [Migration("20260523173854_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fluxo.Lancamentos.Service.Core.Competencia", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("DataCompetencia")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Competencia", (string)null);
                });

            modelBuilder.Entity("Fluxo.Lancamentos.Service.Core.Lancamento", b =>
                {
                    b.Property<Guid>("IdLancamento")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DataCompetencia")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("IdLancamento");

                    b.ToTable("Lancamentos", (string)null);

                    b.HasDiscriminator<string>("TipoEvento").HasValue("Lancamento");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Fluxo.Lancamentos.Service.Core.Creditar.CreditoEfetuadoEvent", b =>
                {
                    b.HasBaseType("Fluxo.Lancamentos.Service.Core.Lancamento");

                    b.HasDiscriminator().HasValue("Credito");
                });

            modelBuilder.Entity("Fluxo.Lancamentos.Service.Core.Debitar.DebitoEfetuadoEvent", b =>
                {
                    b.HasBaseType("Fluxo.Lancamentos.Service.Core.Lancamento");

                    b.HasDiscriminator().HasValue("Debito");
                });

            modelBuilder.Entity("Fluxo.Lancamentos.Service.Core.Estornar.EstornoEfetuadoEvent", b =>
                {
                    b.HasBaseType("Fluxo.Lancamentos.Service.Core.Lancamento");

                    b.Property<Guid>("IdEstornado")
                        .HasColumnType("uuid");

                    b.HasDiscriminator().HasValue("Estorno");
                });
#pragma warning restore 612, 618
        }
    }
}
