<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
        <PackageReference Include="MongoDB.Driver" Version="3.12.0" />
        <PackageReference Include="RabbitMQ.Client" Version="7.2.2" />
        <PackageReference Include="Scalar.AspNetCore" Version="2.17.13" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Fluxo.Abstractions\Fluxo.Abstractions.csproj"/>
        <ProjectReference Include="..\Fluxo.Contracts\Fluxo.Contracts.csproj"/>
        <ProjectReference Include="..\Fluxo.ServiceDefaults\Fluxo.ServiceDefaults.csproj"/>
    </ItemGroup>

</Project>
